localsend/localsend

assets/i18n/strings_zh_Hans.i18n.json

A Simplified Chinese translation.

Add Simplified Chinese translation.

---

assets/i18n/_missing_translations.json
assets/i18n/strings_ko.i18n.json

I translate `strings_ko.i18n.json`.
I tested app and it is perfectly translated into korean.

Add: korean translation

---

assets/i18n/_missing_translations.json
assets/i18n/strings_fr-FR.i18n.json

I may have forgotten to update a file, let me know and I will update the PR.

feat(i18n): add fr_FR translation

---

assets/i18n/strings_in.i18n.json

I made Indonesian translation, hope it merged. Let me know if anything goes wrong.

feat(i18n): add indonesian (in) translation

---

assets/i18n/_missing_translations.json
assets/i18n/strings_ko.i18n.json

Add missing korean translations

---

assets/i18n/strings_zh-Hant_HK.i18n.json

This translation is based on the previous PR, while taking both language and vocabulary differences into consideration.

Traditional Chinese (Hong Kong) Translation

---

assets/i18n/strings_zh-Hans.i18n.json

Add translation about encryption.

i18n: update Simplified Chinese translation

---

assets/i18n/_missing_translations.json
assets/i18n/strings_it.i18n.json

This pull request adds the missing parameters in the Italian to English translation, enhancing the localization of the project.

feat(i18n): addition of missing translation parameters in italian

---

assets/i18n/strings_ja.i18n.json

We should probably discuss about it in another place, but have you considered using a translation management service like Crowdin, Weblate, POEditor, Transifex, and etc? While they are mostly paid services, some of them also offer free tiers for open source projects.

Update Japanese locale

---

assets/i18n/strings_tr.i18n.json

@anilsahindev reviewed my pr( #107 ) and he's right. 
I standardized the binary words in turkish 🇹🇷 .

i18n: 🇹🇷 Turkish binary words standardized to 'Binary word'

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

Add github basic issue template, make issue more standardized

add: github basic issue template

---

assets/i18n/strings_es-ES.i18n.json

This PR adds the Spanish translation strings file. I closed the previous one because I had messed it up. Now everything should be fine.

Add Spanish translation strings file.

---

assets/i18n/_missing_translations.json
assets/i18n/strings_fr-FR.i18n.json

Added missing translations for French.

Added fr-FR missing translations

---

assets/i18n/strings_tr.i18n.json

Missing 🇹🇷 turkish translations added.

i18n: Add missing tr translations

---

assets/i18n/strings_pt-BR.i18n.json
lib/pages/receive_history_page.dart
lib/util/native/open_file.dart
lib/widget/dialogs/cannot_open_file_dialog.dart

Small changes to bring a more natural feel to the reading experience.

i18n update & File not found dialogue tweak

---

lib/provider/persistence_provider.dart
lib/provider/window_dimensions_provider.dart
lib/widget/watcher/window_watcher.dart

I meant to commit this with the previous Pull Request, but it was merged a couple of minutes before I could push it 😅
Sorry hahah

Minor Window Dimensions refactor

---

pubspec.yaml

please see https://github.com/Ephenodrom/Dart-Basic-Utils/issues/85

update basic_utils dependency

---

README.md

Hello everyone!
I added the contributors in the readme.md file in the repository: localsend/localsend. I would like to contribute to this pull-request and I hope you all accept it.
what do you all think of this idea?

add contributors in localsend/localsend

---

assets/i18n/_missing_translations_zh_Hant_TW.json
assets/i18n/strings_zh-Hant_TW.i18n.json

Update and optimize the translations

Update zh-Hant_TW.i18n strings

---

README.md

The last piece in the puzzle. I also updated the Scoop link to point to the permalink on the website.
Resolves #57

Add Chocolatey installation & Update Scoop link

---

assets/i18n/_missing_translations_fr_FR.json

[Related to this comment](https://github.com/localsend/localsend/issues/345#issuecomment-1511034880) (1.9.0 release)
Should be all good

Added missing fr_FR translations

---

pubspec.yaml

https://github.com/leanflutter/flutter_distributor/blob/8e55decfeae942bdf631f2b2b61912b3a25dc39a/packages/flutter_app_packager/lib/src/makers/deb/make_deb_config.dart#LL278C4-L278C4

Added homepage to pubspec file

---

lib/pages/receive_page.dart

feat: open link in new browser tab

---

lib/pages/tabs/settings_tab.dart

Changed settings to use switch #556

---

android/app/src/main/AndroidManifest.xml
lib/provider/network/server/controller/receive_controller.dart
lib/util/native/file_saver.dart
pubspec.lock
pubspec.yaml

This will 
- close #430 
- close #237

Migrate `image_gallery_saver` to `gal`

---

lib/pages/tabs/send_tab.dart
lib/provider/network/nearby_devices_provider.dart
lib/provider/network/scan_provider.dart

feat: tapping on sync button clears found devices

---

android/app/src/main/AndroidManifest.xml
lib/pages/receive_options_page.dart
lib/pages/tabs/settings_tab.dart
lib/util/native/file_picker.dart
lib/util/native/pick_directory_path.dart
pubspec.lock
pubspec.yaml

feat: migrate to file_selector package

---

assets/CHANGELOG.md
lib/provider/device_info_provider.dart
lib/theme.dart
lib/util/native/device_info_helper.dart

fix: navigation bar color on Android 9 and earlier

---

assets/CHANGELOG.md
ios/Podfile.lock
lib/pages/tabs/settings_tab.dart

Hide color setting if dynamic colors are not supported anyways

Hide color setting if not supported

---

assets/i18n/strings.i18n.json

https://github.com/localsend/localsend/pull/671

Add tray/menu bar

---

assets/CHANGELOG.md
assets/i18n/strings.i18n.json
assets/i18n/strings_de.i18n.json
lib/main.dart
lib/model/persistence/color_mode.dart
lib/pages/tabs/settings_tab.dart
lib/theme.dart
lib/widget/dialogs/no_files_dialog.dart

- feat: use filled button for no files dialog
- feat: add OLED color mode

feat: add OLED color mode

---

app/lib/pages/home_page.dart

previous:
beyond:
I have merged the latest code. The error message in the picture is the original error, not mine!

fix: rail padding

---

app/assets/CHANGELOG.md
app/lib/init.dart
app/pubspec.lock
app/pubspec.yaml

Enable high framerate

---

app/assets/i18n/strings_eu.json

This PR adds Basque (eu) language translation. Thanks!

Add basque (eu) language translation

---

CONTRIBUTING.md
app/assets/i18n/strings_it.i18n.json

Add missing translations for Italian

i18n: Add missing Italian translations

---

app/assets/i18n/_missing_translations_vi_VN.json
app/assets/i18n/strings_vi-VN.i18n.json
app/lib/gen/strings.g.dart
app/lib/gen/strings_vi_VN.g.dart

Add translation for Vietnamese and generate Flutter files for it.

i18n: Add Vietnamese

---

app/assets/i18n/_missing_translations_fr_FR.json
app/assets/i18n/strings_fr-FR.i18n.json

Add missing translations for french language

Add missing french translations

---

CONTRIBUTING.md

Add translator to CONTRIBUTING.md.

add Vietnamese translator

---

app/assets/i18n/_missing_translations_cs.json
app/assets/i18n/strings_cs.i18n.json

Added missing translation, hopefully I haven't messed up anything, since I did it manually.

Update Czech translation

---

app/assets/i18n/strings.i18n.json
app/lib/gen/strings.g.dart
app/lib/gen/strings_en.g.dart
app/lib/pages/receive_history_page.dart
app/lib/widget/dialogs/history_clear_dialog.dart
app/pubspec.yaml

I added a dialog box when the user presses the Delete history button, asking for reconfirmation to delete history. I addressed issue #660. I just coded a box in receive_history_page.dart for now, can also make a widget for reconfirmation.

ADD: Alert while deleting  history

---

app/lib/model/cross_file.dart
app/lib/model/state/send/send_session_state.dart
app/lib/model/state/send/sending_file.dart
app/lib/model/state/send/sending_file.mapper.dart
app/lib/pages/progress_page.dart
app/lib/pages/selected_files_page.dart
app/lib/pages/tabs/send_tab.dart
app/lib/provider/network/send_provider.dart
app/lib/provider/selection/selected_sending_files_provider.dart
app/lib/util/determine_image_type.dart
app/lib/util/file_path_helper.dart
app/lib/util/native/file_picker.dart
app/lib/widget/dialogs/add_file_dialog.dart
app/lib/widget/file_thumbnail.dart
app/lib/widget/watcher/shortcut_watcher.dart

feat: paste image

---

app/assets/i18n/_missing_translations_es_ES.json

Hi, i update spanish translations. Saludos.

i18n: update spanish translations

---

app/assets/i18n/strings_vi.i18n.json

Update some small grammar before the new release.
#345

i18n: Vietnamese. Use more common grammar

---

app/assets/i18n/_missing_translations_vi.json

Add missing translation. Refer #806

i18n: Vietnamese. Add missing translations.

---

app/assets/i18n/_missing_translations_bn.json
app/assets/i18n/strings_bn.i18n.json

Added all missing Bangla translations for the next coming release (https://github.com/localsend/localsend/issues/345)

Updated missing translations bn

---

app/assets/i18n/strings_ko.i18n.json

Added missing korean translation #345

i18n: update missing ko translations

---

app/assets/i18n/strings_fil-PH.i18n.json

Added fil-PH (Filipino) translation

feat(i18n): add fil translation

---

app/lib/pages/tabs/settings_tab.dart

Allow to change to **OLED color theme** if it's not supported by OS

---

app/assets/i18n/_missing_translations_ar.json

In this PR, I have Updated the strings in the `_missing_translation_ar.json` file.

i18n: Update Arabic Translation

---

app/assets/i18n/_missing_translations_pt_BR.json
app/lib/pages/about/translators.dart

Hi! I just translated the missing PT-BR translations.

Update pt-br translations

---

app/lib/model/state/server/receive_session_state.dart
app/lib/model/state/server/receive_session_state.mapper.dart
app/lib/pages/receive_page.dart
app/lib/pages/send_page.dart
app/lib/pages/tabs/send_tab.dart
app/lib/provider/network/server/controller/receive_controller.dart
app/lib/widget/list_tile/device_list_tile.dart

feat: use favorite name in the device list

---

scripts/compile_windows_exe-inno.iss

fix: set correct architectures in the Inno config

---

app/lib/provider/persistence_provider.dart
app/lib/util/shared_preferences_portable.dart
app/pubspec.lock
app/pubspec.yaml
app/windows/flutter/CMakeLists.txt

Closes #667 
If a file named `settings.json` exists next to the executable, then this file will be used to store the settings.

feat: prefer portable settings

---

app/assets/i18n/_missing_translations_it.json
app/assets/i18n/strings_it.i18n.json
app/lib/pages/about/translators.dart

https://github.com/localsend/localsend/issues/345

i18n: update Italian translations

---

app/assets/i18n/_missing_translations_fr.json
app/assets/i18n/strings.i18n.json

Added FR translations for https://github.com/localsend/localsend/issues/345#issuecomment-1832988591
\+ While at it found out that there are 2 occurences of "open-source" in the main file, except one was written as "open-source" and the other one "open source", just made it so that both are now "open-source"

Added FR translations + small change to english strings

---

app/lib/pages/progress_page.dart
app/lib/provider/network/server/controller/receive_controller.dart

feat: add countdown when auto finish is enabled

---

app/lib/model/persistence/favorite_device.dart
app/lib/model/persistence/favorite_device.mapper.dart
app/lib/provider/network/nearby_devices_provider.dart
app/lib/provider/network/server/controller/receive_controller.dart
app/lib/widget/dialogs/favorite_edit_dialog.dart

feat: update favorite device name if unchanged

---

app/lib/widget/big_button.dart
app/lib/widget/responsive_list_view.dart

feat: file picker button should expand if text is too long

---

app/assets/i18n/_missing_translations_id.json
app/assets/i18n/strings_id.i18n.json

Manual translation from English to Bahasa Indonesia. Please review and merge.

i18n: update id missing translations

---

app/assets/i18n/strings_it.i18n.json

Update Italian translation

---

app/assets/i18n/strings.i18n.json
app/lib/pages/about/translators.dart

Simple changes to the English strings of the UI to be more professional.
E.g. wifi > Wi-Fi
Iphone > iPhone

Clean up some strings

---

README_ZH.md
app/assets/i18n/strings_zh-CN.i18n.json

更改了个别 中文 翻译(更通俗易懂,更人性化)
Individual Chinese translations have been changed (easier to understand and more humane).

更改了个别中文翻译,Individual Chinese translations have been changed

---

app/assets/i18n/_missing_translations_pl.json
app/assets/i18n/strings_pl.i18n.json

Missing translation and some fixes.

i18n: Update Polish translation

---

app/assets/i18n/_missing_translations_it.json
app/assets/i18n/strings_it.i18n.json

Add latest translations for the upcoming release. :)

 i18n: Update Italian translation

---

app/assets/CHANGELOG.md
app/lib/model/state/server/receive_session_state.dart
app/lib/model/state/server/receive_session_state.mapper.dart
app/lib/pages/receive_history_page.dart
app/lib/provider/network/server/controller/receive_controller.dart
app/lib/util/native/directories.dart
app/lib/util/native/file_saver.dart
app/pubspec.lock
app/pubspec.yaml

fix(android): save files to SD card on Android 10 or lower

---

app/assets/i18n/_missing_translations_ko.json
app/assets/i18n/strings_ko.i18n.json

Update missing korean translations #345

i18n: update korean translationos

---

README_ZH.md
app/assets/i18n/_missing_translations_zh_HK.json
app/assets/i18n/strings_zh-CN.i18n.json
app/assets/i18n/strings_zh-HK.i18n.json

OMG I forgot to push the changes and open a PR before the release

Update zh-HK Translation

---

app/android/app/build.gradle
app/android/app/src/debug/AndroidManifest.xml

https://github.com/localsend/localsend/issues/1121

feat: debug package for android

---

README_ZH.md

1. fix a link
2. add a white space and delete a white line

Fix zh readme

---

app/assets/i18n/strings_rs.i18n.json

Added Serbian translation file /app/assets/i18n/strings_rs.i18n.json

Serbian language translation strings

---

app/lib/util/native/tray_helper.dart
app/lib/widget/watcher/window_watcher.dart

fix: tray area icon won't disappear

---

app/assets/i18n/strings.i18n.json
app/lib/gen/strings_en.g.dart
app/lib/gen/strings_zh_CN.g.dart
app/lib/model/state/settings_state.dart
app/lib/model/state/settings_state.mapper.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/pages/tabs/settings_tab_controller.dart
app/lib/pages/tabs/settings_tab_vm.dart
app/lib/pages/tabs/settings_tab_vm.mapper.dart
app/lib/provider/dio_provider.dart
app/lib/provider/persistence_provider.dart
app/lib/provider/settings_provider.dart
common/lib/src/constants.dart

Improve cases where the timeout is too short to discover devices due to network quality by adding a timeout setting. #1301

add discovery timeout setting

---

app/assets/i18n/strings.i18n.json
app/lib/pages/web_send_page.dart
app/lib/widget/dialogs/zoom_dialog.dart

I added a zoom button to the network share with a new zoom dialog. The dialog shows the url, but maximizes the size based on the screen width. I tested it manually on both a Linux desktop and Android tablet. If there are unit tests to write or other required changes before accepting, please let me know.

#1274 Make share larger

---

app/assets/i18n/_missing_translations_pt_PT.json

update portuguese `pt_PT` translation

i18n: update portuguese translation

---

app/assets/i18n/_missing_translations_it.json
app/assets/i18n/strings_it.i18n.json

Added missing Italian Translations

i18n(it-IT): Added missing Italian Translations

---

app/assets/i18n/strings_fr.i18n.json
app/lib/gen/strings.g.dart
app/lib/gen/strings_fr.g.dart

I've added french translations for my latest PR :)

Add french translation for sanitization

---

app/assets/i18n/strings_ro.i18n.json
app/lib/pages/about/translators.dart

Alright, I finally managed to translate the entire file, although, I will update it more on this pull request as time goes on. (I'm so nervous if it gets declined...)
I'm so excited for my language to be included here! Since I love LocalSend, and the only way I would contribute is translating, while yes, it might consume my time, but atleast more Romanian people will be coming 😊.
Thank you so, so much with the application being the most essential to us! 🩵

Adding the Romanian translation

---

README.md
app/assets/CHANGELOG.md
app/lib/init.dart
app/lib/model/state/settings_state.dart
app/lib/model/state/settings_state.mapper.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/pages/tabs/settings_tab_controller.dart
app/lib/pages/tabs/settings_tab_vm.dart
app/lib/pages/tabs/settings_tab_vm.mapper.dart
app/lib/provider/persistence_provider.dart
app/lib/provider/settings_provider.dart
app/lib/util/native/autostart_helper.dart
app/pubspec.lock
app/pubspec.yaml
app/test/mocks.mocks.dart

Closes #1464
Closes #464, #687, #1231, #1293

feat: remove msix, improve auto start

---

app/assets/CHANGELOG.md
app/lib/pages/tabs/send_tab.dart
app/lib/pages/tabs/send_tab_vm.dart
app/lib/widget/dialogs/favorite_edit_dialog.dart

feat: confirm on favorite tap

---

app/assets/CHANGELOG.md
app/assets/i18n/strings.i18n.json
app/assets/i18n/strings_de.i18n.json
app/lib/gen/strings.g.dart
app/lib/gen/strings_de.g.dart
app/lib/gen/strings_en.g.dart
app/lib/pages/receive_history_page.dart

feat: add option to open parent folder of received files in history

---

app/assets/CHANGELOG.md
app/assets/i18n/strings.i18n.json
app/assets/web/main.js
app/lib/gen/strings.g.dart
app/lib/gen/strings_en.g.dart
app/lib/model/state/send/web/web_send_state.dart
app/lib/model/state/send/web/web_send_state.mapper.dart
app/lib/pages/web_send_page.dart
app/lib/provider/network/server/controller/send_controller.dart
app/lib/provider/network/server/server_provider.dart
app/lib/widget/dialogs/pin_dialog.dart
app/pubspec.lock
app/pubspec.yaml

feat: add option to require PIN when sharing via link

---

app/assets/i18n/strings_en_IN.i18n.json

Added English(India) | Create strings_en_IN.i18n.json

---

app/assets/CHANGELOG.md
app/assets/i18n/strings.i18n.json
app/lib/gen/strings.g.dart
app/lib/gen/strings_en.g.dart
app/lib/model/state/send/web/web_send_state.dart
app/lib/model/state/server/server_state.dart
app/lib/model/state/server/server_state.mapper.dart
app/lib/model/state/settings_state.dart
app/lib/model/state/settings_state.mapper.dart
app/lib/pages/send_page.dart
app/lib/pages/tabs/send_tab.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/pages/web_send_page.dart
app/lib/provider/network/send_provider.dart
app/lib/provider/network/server/controller/common.dart
app/lib/provider/network/server/controller/receive_controller.dart
app/lib/provider/network/server/controller/send_controller.dart
app/lib/provider/network/server/server_provider.dart
app/lib/provider/persistence_provider.dart
app/lib/provider/settings_provider.dart
app/lib/widget/dialogs/pin_dialog.dart
app/pubspec.lock
app/pubspec.yaml
common/lib/src/model/session_status.dart

feat: require pin on receive

---

app/assets/i18n/strings_uk.i18n.json

Sorry for the multiple small shipments, but this should hopefully be the last one for the next release.

i18n: Another tiny fix for the Ukrainian language

---

app/assets/CHANGELOG.md
app/lib/model/cross_file.dart
app/lib/model/cross_file.mapper.dart
app/lib/provider/network/send_provider.dart
app/lib/provider/network/server/controller/receive_controller.dart
app/lib/provider/network/server/controller/send_controller.dart
app/lib/provider/selection/selected_sending_files_provider.dart
app/lib/util/native/cross_file_converters.dart
app/lib/util/native/file_saver.dart
app/test/unit/model/dto/prepare_upload_request_dto_test.dart
common/lib/src/model/device.mapper.dart
common/lib/src/model/dto/file_dto.dart
common/lib/src/model/dto/file_dto.mapper.dart
common/lib/src/model/dto/info_dto.mapper.dart
common/lib/src/model/dto/info_register_dto.mapper.dart
common/lib/src/model/dto/multicast_dto.mapper.dart
common/lib/src/model/dto/prepare_upload_request_dto.mapper.dart
common/lib/src/model/dto/prepare_upload_response_dto.mapper.dart
common/lib/src/model/dto/receive_request_response_dto.mapper.dart
common/lib/src/model/dto/register_dto.mapper.dart
common/lib/src/model/state/isolate_child_state.mapper.dart
common/lib/src/model/state/isolate_common_state.mapper.dart
common/lib/src/model/state/isolate_parent_state.mapper.dart
common/lib/src/model/state/isolate_ref_state.mapper.dart
common/lib/src/model/state/isolate_state.mapper.dart
common/lib/src/model/state/isolate_sync_dto.mapper.dart
common/lib/src/model/stored_security_context.mapper.dart

feat: keep timestamps of transferred files

---

app/assets/CHANGELOG.md
app/lib/util/native/taskbar_helper.dart

fix: crash when files bigger than 2 GB

---

app/assets/i18n/_missing_translations_ro.json

technically, the title shouldn't be this long...
but alright, and, have a great day!

Update the missing translations for the Romanian Translation

---

app/assets/i18n/_missing_translations_vi.json

Late a bit. I haven't noticed there is a new release.

i18n missing_translation_vi.json

---

app/assets/CHANGELOG.md
app/lib/util/native/file_saver.dart

Closes #36
Closes #240 
Closes #1431

Fix memory leak when receiving files

---

app/android/app/src/main/kotlin/org/localsend/localsend_app/MainActivity.kt
app/assets/CHANGELOG.md
app/lib/pages/tabs/settings_tab.dart
app/lib/provider/selection/selected_sending_files_provider.dart
app/lib/util/native/cross_file_converters.dart
app/lib/util/native/file_picker.dart
app/lib/util/native/file_picker_android.dart
app/lib/util/native/file_picker_android.mapper.dart
app/lib/util/native/file_saver.dart

Closes #114
Closes #1249
Closes #1542
Closes #1544

fix(android): save files outside Download folder

---

app/assets/CHANGELOG.md
app/lib/main.dart
common/lib/src/isolate/parent/parent_isolate_provider.dart

fix: properly close app on back gesture

---

app/assets/i18n/_missing_translations_sr.json
app/assets/i18n/_missing_translations_sr_Cyrl.json

Updated missing translations for Serbian language, latin and cyrillic script ( app/assets/i18n/_missing_translations_sr.json , app/assets/i18n/_missing_translations_sr_Cyrl.json )

Update Serbian missing translations

---

app/assets/i18n/_missing_translations_th.json
app/assets/i18n/strings_th.json

Small fix for Thai language translation and Added missing translations for Thai language (th-TH) :)

Update Thai Translation

---

app/assets/i18n/_missing_translations_ko.json
app/assets/i18n/strings_ko.json

I made a minor correction to the Korean translation and added the missing translations.
@mgmix If you have a moment, please review the changes. No pressure!

Update Korean translation

---

app/assets/i18n/strings_hi.json

Add Hindi Translation | Create strings_hi.json

---

LICENSE
app/lib/pages/about/about_page.dart

chore: change to apache 2.0

---

app/assets/i18n/strings.json

As for me "Search devices" sounds more casual.

i18n: Correction for English language

---

app/assets/CHANGELOG.md
app/lib/pages/tabs/send_tab.dart
app/lib/widget/big_button.dart
app/lib/widget/horizontal_clip_list_view.dart

feat(mobile): adjust padding between buttons in send tab to indicate that it's scrollable

---

app/assets/CHANGELOG.md
app/lib/pages/receive_page_controller.dart

feat: treat any URI as link

---

app/assets/i18n/_missing_translations_sr.json
app/assets/i18n/_missing_translations_sr_Cyrl.json

Update _missing_translations_sr.json and _missing_translations_sr_Cyrl.json ( latin and cyrillic script )

Serbian language - update missing translations

---

app/assets/CHANGELOG.md
app/lib/pages/progress_page.dart
app/lib/provider/network/send_provider.dart
app/lib/provider/network/server/controller/receive_controller.dart
app/lib/provider/progress_provider.dart
common/lib/model/file_status.dart

feat: add option to retry failed files

---

README_PL.md

(sorry for the second PR. I missed those details :smile:)

Polish readme: Fix section links, a typo and localize Google Play Store name

---

app/assets/i18n/_missing_translations_es_ES.json

This pull request addresses missing Spanish translations in the _missing_translations_es_ES.json file. The following changes have been made:
Please review the changes and merge if they are correct. If you have any questions or concerns, feel free to leave a comment.

Update _missing_translations_es_ES.json with missing Spanish translations

---

app/lib/pages/tabs/send_tab.dart

fix: selected files box padding in RTL lang

---

app/lib/pages/tabs/send_tab.dart

fix: help icon flipped in RTL lang

---

app/assets/i18n/_missing_translations_fil_PH.json

Added missing translation for Filipino translation

i18n: Fixed missing translation for fil_PH

---

app/assets/i18n/strings_sk.json

Added Slovak translation

---

app/assets/i18n/_missing_translations_sr.json
app/assets/i18n/_missing_translations_sr_Cyrl.json

Updated _missing_translations_sr.json and _missing_translations_sr_Cyrl.json

Update missing translations Serbian

---

app/assets/i18n/_missing_translations_fil_PH.json

Added missing translation in `_missing_translations_fil_PH.json`

Added missing translation for Fil PH

---

app/lib/config/init.dart

closes https://github.com/localsend/localsend/issues/1794

feat(macos): change "start hidden" to minimize to menubar

---

app/lib/provider/network/server/controller/send_controller.dart

fix: ERR_EMPTY_RESPONSE when sharing text via link #1777

---

app/lib/config/init.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/util/native/autostart_helper.dart
app/lib/util/native/macos_channel.dart
app/macos/Runner.xcodeproj/project.pbxproj
app/macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
app/macos/Runner/AppDelegate.swift

https://github.com/localsend/localsend/issues/1242
Not used CocoaPods since the owner [says](https://github.com/sindresorhus/LaunchAtLogin-Legacy/releases/tag/v3.0.0#:~:text=It%20didn%27t%20work%20correctly%20anyway.) taht "It didn't work correctly".
ref https://github.com/sindresorhus/LaunchAtLogin-Legacy/issues/33#issuecomment-2253207190, ref https://github.com/hisaac/CenterMouse/blob/main/CenterMouse/Sources/AppDelegate.swift

feat(macos): add sandboxed launch at login for App Store version

---

app/assets/i18n/strings_it.json

Improved language consistency to better adapt to the different targeted ecosystems. 
Fixed some capitalization mistakes for iOS and Wi-Fi, and characters between parentheses/after the “:” sign. 
After reviewing it for several times today, I think it's a good improvement based on the original translation, which was already pretty clear.

i18n: Updated the Italian translation for consistency.

---

app/lib/util/native/macos_channel.dart
app/macos/Runner/AppDelegate.swift

refactor: remove platform checks in macos_channel.dart

---

app/assets/i18n/_missing_translations_da.json

Update _missing_translations_da.json

i18n: Update missing translations danish

---

README.md
readme_i18n/README_ES.md
readme_i18n/README_JA.md
readme_i18n/README_PH.md
readme_i18n/README_PL.md
readme_i18n/README_PT_BR.md
readme_i18n/README_TH.md
readme_i18n/README_VI.md
readme_i18n/README_ZH.md

- Added pt_BR README.md translation

docs(readme): add pt_BR README.md translation

---

app/assets/i18n/strings_de.json
app/lib/gen/strings_de.g.dart

Correction of minor spelling errors in DE-language files

i18n: Minor spelling errors (DE)

---

app/assets/i18n/strings_ms.json

It supports the Malay language in Malaysia.

i18n: add strings_ms.json

---

app/assets/i18n/_missing_translations_he.json

docs: update _missing_translations_he.json

---

app/assets/i18n/strings_id.json

This pull request addresses several issues with the Indonesian translations in the strings_id.json file:
- Corrected inaccurate translations for certain UI elements.
- Added missing translations to ensure full coverage of the app's features.
- Improved consistency in terminology to provide a better user experience.
Please review the changes and merge if appropriate.

Fix and Update Indonesian Translations in strings_id.json

---

app/assets/i18n/strings_sl-SI.json
app/lib/gen/strings.g.dart
app/lib/gen/strings_sl_SI.g.dart

Add: Slovenian translation

---

app/assets/i18n/_missing_translations_nl.json

Translations added for the 2 new strings.

Translate new strings into Dutch

---

app/linux/my_application.cc

See https://github.com/NixOS/nixpkgs/issues/348345

Fix window visibility bug

---

app/macos/Runner/DebugProfile.entitlements
app/macos/Runner/Info.plist
app/macos/Runner/Release.entitlements
app/macos/Runner/Shared.swift
app/macos/ShareExtension/Info.plist
app/macos/ShareExtension/ShareExtension.entitlements

closes https://github.com/localsend/localsend/issues/1942

fix: "would like to access data from other apps" warning popup on macOS Sequoia

---

app/assets/i18n/_missing_translations_fil_PH.json

Added missing translation for fil-PH

i18n: Added missing translation for fil-PH

---

README.md
app/assets/i18n/_missing_translations_km.json
app/assets/i18n/strings_km.json
readme_i18n/README_ES.md
readme_i18n/README_ID.md
readme_i18n/README_IT.md
readme_i18n/README_JA.md
readme_i18n/README_KM.md
readme_i18n/README_PH.md
readme_i18n/README_PL.md
readme_i18n/README_PT_BR.md
readme_i18n/README_TH.md
readme_i18n/README_VI.md
readme_i18n/README_ZH.md

Update '_missing_translations_km.json' and 'strings_km'. Create a new README for the Khmer language, and mention the Indonesian markdown file in each README that are missing.

Update '_missing_translations_km.json' and 'strings_km'

---

app/assets/i18n/strings_es-ES.json
app/lib/gen/strings_es_ES.g.dart

Hi, i add fixes to spanish translation [#345](https://github.com/localsend/localsend/issues/345#issuecomment-2439799541)

i18n: Minor translation changes for spanish

---

app/assets/i18n/_missing_translations_ru.json
app/assets/i18n/_missing_translations_uk.json
app/assets/i18n/strings.json

Okay. Corrections have been made taking your feedback into account.

i18n: Updates for missing translations for Ukrainian and Russian. Also, a minor correction for English 

---

app/assets/i18n/_missing_translations_vi.json
readme_i18n/README_VI.md

add missing_translations_vi and fix readme_vi

---

app/lib/config/init.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/util/native/macos_channel.dart
app/macos/Runner/AppDelegate.swift
app/macos/Runner/Release.entitlements
app/macos/Runner/Shared.swift

closes https://github.com/localsend/localsend/issues/1971

fix(macos): persist destination folder access across app launches

---

app/assets/i18n/_missing_translations_ro.json

Finally, the updated missing translations are finished. unless there's new stuff that I have to translate later...
This pull request could remain open until when the new release is almost ready, just in case if there were new strings to translate, or it could just be merged to not clutter the pull requests tab.
Just, thank you so much for creating a project that's really essential, I'd most definitely rate it 5 stars. :D
(sorry for including in a pull request, but I just can't stop appreciating it, lol)
Hope this makes you smile today, have an amazing great day for developing!

Update _missing_translations_ro.json - Romanian Translation

---

app/assets/i18n/strings_fi.json
app/lib/gen/strings_fi.g.dart

A small fix, capitalize only the first letter on needRestart

Update Finnish translation

---

app/assets/i18n/_missing_translations_nl.json

Add missing translations to _missing_translations_nl.json

Update Dutch translation

---

app/assets/CHANGELOG.md
app/lib/pages/progress_page.dart
app/lib/pages/receive_history_page.dart
app/lib/util/native/open_folder.dart
app/lib/widget/dialogs/open_file_dialog.dart
app/linux/flutter/generated_plugin_registrant.cc
app/linux/flutter/generated_plugins.cmake
app/macos/Flutter/GeneratedPluginRegistrant.swift
app/pubspec.lock
app/pubspec.yaml
app/windows/flutter/generated_plugin_registrant.cc
app/windows/flutter/generated_plugins.cmake

feat: highlight file when tapping "Show in folder"

---

README.md
readme_i18n/README_FA.md

i18n: add Farsi README

---

readme_i18n/README_TR.md

Turkish language support has been added to readme.

Turkish Language

---

app/assets/i18n/strings.json

Currently translated at 100.0% (369 of 369 strings)
Translate-URL: https://hosted.weblate.org/projects/localsend/app/en/
Translation: LocalSend/App

Translated using Weblate (English)

---

README.md
readme_i18n/README_TR.md

Turkish language link add to README.md

---

app/lib/pages/progress_page.dart

Closes #1510 where the screen would turn off while transferring large files, disrupting the transfer process. 
To solve this, `WakelockPlus.enable()` is called periodically to ensure the device remains awake throughout the file transfer session and to handle cases where the OS may release the wakelock unexpectedly. According to the WakelockPlus's documentation, there is no negative impact in calling `WakelockPlus.enable()` more often.

fix: keep screen awake during large file transfers

---

README.md
readme_i18n/README_ZH.md

docs: add getting started steps

---

app/lib/pages/progress_page.dart

Used Flutter’s TweenAnimationBuilder to provide animation interpolation for the value change of CustomProgressBar, making the LocalSend experience smoother.

Provided Animation for Progress Bar

---

README.md
app/assets/i18n/_missing_translations_ko.json
app/assets/i18n/strings_ko.json
readme_i18n/README_ES.md
readme_i18n/README_FA.md
readme_i18n/README_FR.md
readme_i18n/README_ID.md
readme_i18n/README_IT.md
readme_i18n/README_JA.md
readme_i18n/README_KM.md
readme_i18n/README_KO.md
readme_i18n/README_PH.md
readme_i18n/README_PL.md
readme_i18n/README_PT_BR.md
readme_i18n/README_TH.md
readme_i18n/README_TR.md
readme_i18n/README_VI.md
readme_i18n/README_ZH.md

- Added / Updated Korean translations
- Added Korean README.md file
- Edited all README files to include same README files in other languages

l10n: Update Korean Translation

---

app/lib/pages/about/translators.dart

Hi, I hope everything is going great, I forgot to add myself as a collaborator.

Add me as a contributor

---

app/assets/CHANGELOG.md
app/lib/widget/watcher/shortcut_watcher.dart

fix: window disappears on command key

---

app/assets/CHANGELOG.md
app/assets/i18n/en.json
app/lib/config/init.dart
app/lib/gen/strings.g.dart
app/lib/gen/strings_en.g.dart
app/lib/model/state/settings_state.dart
app/lib/model/state/settings_state.mapper.dart
app/lib/pages/settings/network_interfaces_page.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/pages/tabs/settings_tab_controller.dart
app/lib/provider/local_ip_provider.dart
app/lib/provider/persistence_provider.dart
app/lib/provider/settings_provider.dart
app/lib/widget/dialogs/text_field_tv.dart
app/pubspec.lock
app/pubspec.yaml
app/test/mocks.mocks.dart
cli/pubspec.lock
common/lib/src/isolate/child/multicast_discovery_isolate.dart
common/lib/src/isolate/child/sync_provider.dart
common/lib/src/isolate/child/sync_provider.mapper.dart
common/lib/src/isolate/parent/actions.dart
common/lib/src/isolate/parent/actions_sync.dart
common/lib/src/isolate/parent/parent_isolate_provider.dart
common/lib/src/isolate/parent/parent_isolate_provider.mapper.dart
common/lib/src/task/discovery/multicast_discovery.dart
common/lib/util/network_interfaces.dart
common/test/unit/util/network_interfaces_test.dart

feat: add advanced setting to filter network interfaces

---

app/lib/pages/about/translators.dart
readme_i18n/README_TR.md

feat: update turkish language

---

scripts/Languages/ChineseSimplified.isl
scripts/compile_windows_exe-inno.iss

add inno chinesesimplified support

---

app/lib/provider/selection/selected_sending_files_provider.dart
app/lib/util/native/send_ignore.dart
app/pubspec.lock
app/pubspec.yaml

though most features could be achieved, some are wired
`**.dart` would not match /some.dart
`**/**.dart` would not match some.dart

.sendignore basics done

---

readme_i18n/README_ES.md

Updated the Spanish README file to reflect recent updates from the original English README

docs(readme): Update README_ES.md

---

app/assets/i18n/zh-TW.json

Update zh-TW with some improvements in pr
https://github.com/localsend/localsend/pull/2304

i18n: improve zh-TW

---

readme_i18n/README_IT.md

Updated README_IT according to the newest README version.

Updated README_IT.md

---

readme_i18n/README_MS.md

will update and translate other things to Malay in the near future

add the Malay translation for the README file

---

app/lib/util/file_path_helper.dart

Fixed https://github.com/localsend/localsend/issues/2706

fix: detect DNG files as image
