assets/i18n/strings_ja.i18n.json

Hi, I just found and tried this app, and it's working really great! I was waiting for an open-source, cross-platform alternative to AirDrop like this so that I can move files between my Linux laptop and iOS devices.
I made a Japanese localization for the app and I hope it gets merged. I don't have Flutter installed so I haven't tested it in real app, but I was able to look around and find where each string is used, so I believe the translations are not out of context.

Add Japanese localization

---

lib/widget/dialogs/message_input_dialog.dart

- multiline checkbox of message input dialog changes behavior of text field, making it horizontally scrollable when disabled
closes #73

fix: multiline property of message input dialog

---

assets/i18n/strings_pl.i18n.json

This PR fixes some grammar and spelling mistakes, and also some bad translation attempts (e.g. `padZero` being translated as "a (mouse)pad with zeros").
There are still a couple of things to improve but I don't have enough context to provide accurate translations.

Fixed a few bad translations (Polish)

---

assets/i18n/strings_zh-Hant_TW.i18n.json

#44 used https://zhconvert.org/ to convert individual characters from simplified to traditional, but none or few differences in vocabulary and terms are taken into consideration. https://opencc.byvoid.com/ did a great job on the conversion.

Improve Traditional Chinese Translation

---

assets/i18n/strings_tr.i18n.json

Add Turkish 🇹🇷 translation with file: `/assets/i8n/strings_tr.i18n.json`
I have a question for better translation. In Line 116 how can you use `receiveOptionsPage.appDirectory`? I can't build and run the app so I can't tested if there is a problem. If somebody send me a photo of the usage I can translate it and commit again.

Turkish(tr) translation

---

.github/dependabot.yml
.github/workflows/winget.yml

v2 fixes a critical error in the action: https://github.com/vedantmgoyal2009/winget-releaser/issues/84
Additionally, add Dependabot to bump dependencies automatically.

ci: bump Winget Releaser to v2 & add dependabot

---

assets/i18n/_missing_translations_pt_BR.json
assets/i18n/strings_pt-BR.i18n.json

Cleared the latest missing translations backlog and applied translations with slang apply to strings_pt-br. 
Changes to take be aware:
- The recentlyUsed field has been translated to "Recém conectado" ( Recently connected ), that implies a list of recently IP addresses that had a successful connection.
Note: The "(Download)" string translates 1:1 to Portuguese, so it was applied as it is.

i18n: update to pt-br translation

---

lib/init.dart
lib/provider/persistence_provider.dart
lib/provider/window_dimensions_provider.dart
lib/widget/watcher/window_watcher.dart

Initial setup to enable restoring the position and size of the app! 
- Setting up Persistence for the required App Window data ☑
- Changes to `init.dart` ☑
- Interface changes to accommodate the option to allow the feature ☒
- Setting up Persistence for the boolean config value ☒
Currently the information is saved on the window watcher onWindowClose method but, perhaps, some other method would be more suitable.
Solves #296

feat: Restore window size and position

---

README.md

use markdown link definition feature, split link text and link definition
more see https://commonmark.org/help/tutorial/07-links.html

docs: improve readme maintainability

---

README.md
lib/util/native/device_info_helper.dart
lib/util/platform_strings.dart

source: https://www.apple.com/legal/intellectual-property/trademark/appletmlist.html

fix: typo error (MacOS -> macOS)

---

lib/pages/receive_options_page.dart

Receive options dropdown resized

---

assets/i18n/_missing_translations_ko.json
assets/i18n/strings_ko.i18n.json

I've finished translating the missing_translations_en file, and execute `slang analyzer --split-missing` locally
it seems to have gone well. (Changes made by analyzer were not committed.)

i18n: Update missing ko locale

---

AppImageBuilder.yml

This is a bit of a mess, I figured it would be easy to move around libayatana-appindicator3-1's dependency tree, but in all truth it is a complete mess.
It bundles the entirety of the gtk3 lib that in turn pulls some obligatory dependencies, but somehow different associated ayatana libs also pull systemd by default that could or not be useful for a headless mode. Not to mention that some few distros don't ship with some version of GTK... so in theory it's practical to have it.
I did try to experiment excluding several dependencies and got to the point of making an AppImage that weighed 54 mB (that worked), but ultimately I decided to just leave adwaita-icon-theme out because the app doesn't implement [https://pub.dev/packages/adwaita](https://pub.dev/packages/adwaita), unfortunately this …

Working dependency for Arch

---

.gitignore
linux/packaging/deb/make_config.yaml

Changes in "For distributors":
Build the executable in Debian 11 ( recommended )
Install flutter distributor
```
dart pub global activate flutter_distributor
``` 
Configure .pub-cache on PATH
```
echo 'export PATH="$PATH:$HOME/.pub-cache/bin"' >> ~/.bashrc
``` 
Generate the .deb package
```
flutter_distributor package --platform linux --targets deb
```

[Distribution] Added debian package configuration

---

pubspec.lock
pubspec.yaml

Some important fixes were made: 
* On-close event handler is fixed
* setMinimumSize and setMaximumSize is fixed on macOS, although not yet on Linux.

deps: window_manager bump

---

.github/workflows/winget.yml

Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.

ci: change Winget Releaser job to `ubuntu-latest`

---

assets/CHANGELOG.md
lib/pages/progress_page.dart

The progress indicator is wrong sometimes because its total size/count value is calculated once by looking for files with tokens.
The calculation happens initially assuming that no files has been sent yet (because each receive request will set the token `null`).
On very fast networks, the request is already received leading to an invalid amount of files with tokens.
The solution is to look for the `status == skipped` condition because this should never change.

fix: possible race condition leading to zero files

---

linux/my_application.cc

I tested the following five situations, all as expected
```fish
GTK_CSD=0 flutter run
GTK_CSD=1 flutter run
GTK_CSD=test flutter run
unset GTK_CSD && flutter run
gtk3-nocsd flutter run
```
ref: 
gtk_csd: https://docs.gtk.org/gtk4/running.html#gtk_csd
gtk3-nocsd: https://github.com/PCMan/gtk3-nocsd
#666

fix: disable gtk client side decorations when the environment variable GTK_CSD exists and its value is 0

---

assets/CHANGELOG.md
lib/pages/home_page.dart
lib/pages/tabs/receive_tab.dart
lib/provider/ui/home_tab_provider.dart
lib/widget/rotating_widget.dart

The current spin animation (the logo above the alias) consumes a lot of resources.
This PR implements a more performant approach.
Closes #510
Closes #535

feat: drastically improve GPU usage by optimizing the spin animation

---

lib/util/native/get_destination_directory.dart

Fixes: #461 
When the system does not have the default Downloads folder defined (`XDG_DOWNLOAD_DIR` for Linux, `374DE290-123F-4565-9164-39C4925E467B` folderId in Windows) the application fails to send the files with an 500 response.
The PR aims to fix it by manually defaulting to the Downloads folder by absolute path
On Linux by using the `$HOME` variable, which should be defined by default
On Windows by using the `HOMEPATH` variable

fix: Fallback to "$HOME/Downloads" when default downloads folder is unavailable

---

assets/i18n/strings.i18n.json
lib/util/native/file_picker.dart
pubspec.yaml

fixes https://github.com/localsend/localsend/issues/568
fixes https://github.com/localsend/localsend/issues/210
This PR add feature to send files that are copied to the clipboard 
https://www.loom.com/share/929b2113cc4a487e9b78781c0e30facd
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

Support file/image transfer by pasting files from the clipboard.

---

app/assets/i18n/_missing_translations_ru.json
app/assets/i18n/_missing_translations_uk.json

OLED has no suitable equivalents in either Ukrainian or Russian, as it is an abbreviation, so everyone uses OLED.

i18n: Update missing translation for Ukrainian and Russian language (uk-UK; ru-Ru)

---

CONTRIBUTING.md

`#` stands for headline, so the note should not be bolded with `#`, but with `**` instead.

docs: use ** instead of ####

---

app/assets/i18n/_missing_translations_pl.json
app/assets/i18n/strings_pl.i18n.json

I updated _missing_translations_pl.json and changed "Jasność" to "Motyw", which is a more accurate translation of "Theme"

i18n: Update Polish translation

---

app/lib/widget/watcher/shortcut_watcher.dart
app/lib/widget/watcher/window_watcher.dart

With these changes, macOS users can now comfortably use Command+W to close the window while preserving the app in the menubar, just like with other apps. I think this improves the consistency of user experience.
This is my first-ever pull request, so please bear with me if there are any issues, whether in the process of creating this PR or in the code itself ^^

Added feature for macOS: command+w to close the window without quiting the app

---

app/lib/provider/selection/selected_sending_files_provider.dart
app/lib/util/native/cross_file_converters.dart

linked to #903 
I try to add validation for already selected files from menu options file, media or folder.
https://github.com/localsend/localsend/assets/7869219/843a0615-a9de-4d90-9c89-6ebc39572872
https://github.com/localsend/localsend/assets/7869219/7ef7ccd1-b6e3-4ec7-8794-b790eb104439
https://github.com/localsend/localsend/assets/7869219/1c17290e-a86c-44a0-bcf3-1c81348727fd
https://github.com/localsend/localsend/assets/7869219/ec4923ee-7900-4834-a5f4-0e9bf3687755

add duplicate files validation when pick image or files or directory

---

app/assets/i18n/strings_fil-PH.i18n.json
app/lib/pages/about/translators.dart

- Fixed Filipino Translation Typo.
- Fixed Filipino Translation grammar on some texts.
- Reviewed `_missing_translations_fil_PH.json` . No changes as same text will apply.
- Added surname on translator page 😄.

i18n: Fixed Filipino Translation Typo and Grammar

---

app/assets/i18n/_missing_translations_tr.json
app/assets/i18n/strings_tr.i18n.json

The last missing translation added to the i18n tr documentation. 
Looks like localsend is fully compatible with Turkish ( :tr: ) language.

i18n/tr Translated missing turkish words

---

app/lib/gen/strings_en.g.dart
app/lib/gen/strings_zh_CN.g.dart
app/lib/gen/strings_zh_HK.g.dart
app/lib/gen/strings_zh_TW.g.dart
app/lib/model/state/settings_state.dart
app/lib/model/state/settings_state.mapper.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/pages/tabs/settings_tab_controller.dart
app/lib/pages/web_send_page.dart
app/lib/provider/network/server/controller/send_controller.dart
app/lib/provider/network/server/server_provider.dart
app/lib/provider/persistence_provider.dart
app/lib/provider/settings_provider.dart

implements for #1114 
add allow anonymous Access the link share file, 
append global setting and  onece share settting
yes, you also can be setting on share link page, if global setting is off:
global settting will be auto override to the  share link page setting:

Bugfix 1114

---

app/lib/provider/network/server/controller/send_controller.dart

fix #1124 
use remote ip as every request session, has no more seession will be created on refresh browser

refactor: use ip as request session

---

app/assets/i18n/_missing_translations_el.json
app/assets/i18n/strings_el.i18n.json

missing el (greek) translations, translated and added to strings_el.i18n.json

i18n: el added missing translations

---

app/lib/provider/network/send_provider.dart
app/lib/provider/network/server/controller/send_controller.dart

Fixes #1062, fixes #1000
Since the broadcast stream cancels itself when there are no current subscribers, it can properly release file handles even if the read stream is interrupted.
I have tested it on my Windows PC and it works as expected and it should work fine on other machines.
Reference: [Stream.asBroadcastStream()](https://api.flutter.dev/flutter/dart-async/Stream/asBroadcastStream.html)

fix: Close file stream properly

---

app/lib/util/native/tray_helper.dart
app/linux/flutter/generated_plugin_registrant.cc
app/linux/flutter/generated_plugins.cmake
app/macos/Flutter/GeneratedPluginRegistrant.swift
app/pubspec.lock
app/pubspec.yaml
app/windows/flutter/generated_plugin_registrant.cc
app/windows/flutter/generated_plugins.cmake

Using [tray_manager](https://pub.dev/packages/tray_manager) for Linux as well allows ditching of the unreliable and seemingly less-than-well maintained flutter library [system_tray](https://pub.dev/packages/system_tray) and unifies desktop tray handling across platforms.
At the same time, use upstream `tray_manager` instead of a forked repo (which was stuck on 0.2 and did not contain e.g. leanflutter/tray_manager#38 ). This additionally enables building on Linux again since Tienisto's forked repo used to disable the Linux plugin: Tienisto/tray_manager@b37f5e0. This also works around issues with newer libayatana-appindicator versions: leanflutter/tray_manager#38
Caveats discussed previously still apply: https://github.com/localsend/localsend/pull/404
Mainly:
- Flutter versions installed …

Linux: Use tray_manager instead of system_tray; remove system_tray

---

app/lib/pages/tabs/send_tab.dart

As mentioned in the linked issue, this PR adds a new button on the `send_tab` element of the "Send Page". This button clears the current file selection. The reason behind this is to reduce the UX friction for that action.
See video:
https://github.com/localsend/localsend/assets/38408878/0f05dd53-e055-4a96-b5ba-65d4903b6a36

Add Button to quickly clear selection

---

CONTRIBUTING.md
README.md
README_ZH.md

-> Addresses issue #1258 
As stated in the mentioned issue, the Nix package manager isn't tied specifically to NixOS. This PR simply relabeled all mentions of NixOS.

Rename NixOS to Nixpkgs

---

app/assets/i18n/strings_sv.i18n.json

"Öppen" means (thing) is already open while "Öppna" means to open (thing).

Fixed a grammatic error in Swedish Translation

---

app/assets/i18n/strings.i18n.json
app/lib/gen/strings.g.dart
app/lib/gen/strings_en.g.dart
app/lib/provider/network/server/controller/receive_controller.dart
app/lib/util/native/file_saver.dart
app/lib/widget/dialogs/file_name_input_dialog.dart
app/lib/widget/dialogs/quick_actions_dialog.dart
app/pubspec.yaml

-> Fixes issue #1063 #1180 #1101  (And possibly more but I couldn't find)
As discussed in issue #1063 there currently is an error if a file is sent on a device with a different system of the sender. This is due to different character limitations in files' names depending on Operating systems and partitions. For example:
On my Linux computer I can create the file `<cool>.txt` and send it to my other linux computer without issue. But if I try to send it to my Windows computer or to my Android phone, LocalSend will fail to save the file and fail the transfer with error code 500. This is because `<>` are **illegal characters** on Windows and FAT32 devices (Android).
This PR fixes that issue by providing a sanitization step before saving a file. Like here:
```dart
Future<String> …
```

Add filename sanitization

---

app/ios/Runner/Info.plist

This PR can make ios app's documents files visible to the Finder/AppleDevices app.
This allows users to transfer files in the LocalSend documents directory between Mac/Win and iOS devices .
Finder (Mac)
AppleDevices (Windows)

feat: ios app - make documents files visible to the Finder/AppleDevices app

---

app/lib/widget/dialogs/file_info_dialog.dart

Fixes issue #1382 
As discussed and demonstrated in the issue, the text in the FileInfoDialog widget was prone to overflowing and clipping the text content if it was too long.
This PR fixes that by wrapping the Table in a SingleChildScrollView as demonstrated in this screen recording:
[TextOverflow.webm](https://github.com/localsend/localsend/assets/38408878/256d29e1-5b18-4f28-a847-79d7ac82ea3c)

Fix issue 1382: File info dialog overflow

---

README_ZH.md
app/assets/i18n/strings_zh-CN.i18n.json
app/assets/i18n/strings_zh-TW.i18n.json
app/lib/gen/strings_zh_CN.g.dart
app/lib/gen/strings_zh_TW.g.dart

[https://github.com/localsend/website/pull/70](https://github.com/localsend/website/pull/70)
* * *
**Description:**
This pull request aims to improve the Chinese translation of LocalSend by changing the term "共享" to "分享."
**Rationale:**
In Chinese, the terms "共享" and "分享" both refer to the act of sharing, but they have slightly different connotations and usage contexts:
1. **共享 (Gòngxiǎng):**
- Typically used in formal or technical contexts.
- Implies mutual access or usage, often with an emphasis on collective benefit. Commonly used for resources, services, or infrastructure.
- Example: "共享经济" (sharing economy), "共享单车" (bike-sharing).
2. **分享 (Fēnxiǎng):**
- More commonly used in everyday language.
- Focuses on the act of giving and receiving, emphasizing the personal and voluntary …

fix: Chinese translate problem 共享 -> 分享

---

app/assets/i18n/strings_ro.i18n.json

Tried to improve grammar and fix mistypes, Update the Fruit and Adjective section with gender feminine instead of being diversed.
There may be mistakes in its translation (I can't really be perfect at that anyways), but I'm not too sure about how to improve them more, to sound... better. but it's alright for now.
I'm just happy that there's Romanian in LocalSend.
If there's something wrong with the Pull Request, tell me.
Thank you.

Updated the Romanian translation

---

app/assets/i18n/_missing_translations_sr.json
app/assets/i18n/_missing_translations_sr_Cyrl.json

Strings in app/assets/i18n/_missing_translations_sr.json and app/assets/i18n/_missing_translations_sr_Cyrl.json updated.

Updated missing translations for Serbian language, latin and cyrilic script

---

app/assets/CHANGELOG.md
app/lib/util/shared_preferences/shared_preferences_portable.dart

fix: use correct portable settings file when started via autostart

---

.github/workflows/winget.yml

Action has moved from `vedantmgoyal2009/winget-releaser@v2` to `vedantmgoyal9/winget-releaser@main`. This should fix the recent workflow failures.

Update Winget Releaser job to latest tag

---

app/windows/runner/CMakeLists.txt
app/windows/runner/main.cpp
app/windows/runner/win32_window.cpp
app/windows/runner/win32_window.h

In the current implementation, the title bar on Windows does not align with the system theme when the dark mode is enabled. Ideally, the app should follow the system theme.
#493
#1375
#1614
[flutter/pull/110615](https://github.com/flutter/flutter/pull/110615)
Create a template project by `flutter create` using the latest Flutter SDK, then replace the `windows/runner` with the updated from the template.
The new code is derived from the official Flutter template, it should not introduce any new issues.

Improvement (Windows): Use dark title bar on dark system theme.

---

app/assets/i18n/strings.json

I should have corrected it earlier when I was fixing it for Ukrainian and Russian languages, but I forgot. Such a parameter name would look more user-friendly.
Also, a question. My English-speaking friend who uses Windows noticed that the parameter quit/exit is named "Quit LocalSend", which meets Apple’s [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines). However, according to the [Windows app development documentation](https://learn.microsoft.com/uk-ua/windows/apps/), Windows apps should use "Exit", as seen in various Windows apps. So, is it possible to use separate translations for the same strings for different platforms?

i18n: Correction for English language

---

app/assets/i18n/strings_it.json

I propose to change the Italian translation of the English word "Done" from "Eseguito" to "Fatto".
The current "Eseguito" is like "Executed", which in my opinion creates confusion as Italians are not used to this word in this context and for a button with the function to close the download section after receiving data.

Update italian translation

---

app/lib/widget/horizontal_clip_list_view.dart

fix: file picker options padding in RTL lang

---

app/lib/config/init.dart
app/lib/util/native/macos_channel.dart
app/macos/Runner.xcodeproj/project.pbxproj
app/macos/Runner/AppDelegate.swift
app/macos/Runner/ContentDropView.swift
app/macos/Runner/Info.plist
app/macos/Runner/Shared.swift
app/macos/ShareExtension/Info.plist
app/macos/ShareExtension/ShareController.swift
app/macos/ShareExtension/Utilities.swift

Added support for sharing web URLs and texts using macOS Share menu, and added support for drag and drop text onto the menu bar item and the Dock icon
Completion of #1716 and #1739

feat(macos): add support for text sharing and dropping

---

app/assets/i18n/_missing_translations_ru.json
app/assets/i18n/_missing_translations_uk.json
app/assets/i18n/strings.json

Since there is no contact list but rather a favorites list, I think it should specify "favorites list" to avoid confusing users (changes for the English).

i18n: Updates for missing translations for Ukrainian and Russian. Also, a minor correction for English

---

app/lib/util/native/macos_channel.dart
app/macos/Runner/AppDelegate.swift

refactor of https://github.com/localsend/localsend/commit/cf48c539fdf36902329f450a8513ace25e9ec7f2
The main point is that the `Defaults.observe` callback is called not only for future changes, but is called first for the initial value.

refactor: simplified `methodChannelInitialized` awaiting

---

app/lib/util/native/macos_channel.dart
app/lib/util/native/taskbar_helper.dart
app/macos/Podfile
app/macos/Podfile.lock
app/macos/Runner/AppDelegate.swift

closes https://github.com/localsend/localsend/issues/1688
Flutter's Swift Package Manager support is only from Flutter version 3.24, and we are stuck on 3.13, so we lose things like https://github.com/sindresorhus/DockProgress/issues/1 (DockProgress dropped CocoaPods support in v4.0.0)
Once we're free, switch to the latest version of DockProgress using the Swift package manager (same as the Default dependency).

feat(macos): show transfer progress in Dock icon

---

app/lib/util/native/taskbar_helper.dart
app/macos/Podfile
app/macos/Podfile.lock
app/macos/Runner.xcodeproj/project.pbxproj
app/macos/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
app/macos/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
app/macos/Runner/AppDelegate.swift

Currently, changing the Dock icon (#1783) breaks DockProgress, so that after one completed transfer, the progress is no longer displayed in the Dock.
The behavior is the same in DockProgress v v4.3.0 but in v4.3.1 it has been fixed, so we have to use the Swift Package Manager through Xcode at the moment to resolve this package (because the cocoapods version will no longer be updated), and then it will be possible to build normally using the flutter command.

fix: dock progress shows only once

---

app/macos/Runner/AppDelegate.swift

When the app is minimized to the menu bar, the expected behavior when reopening the app from the Launchpad is that the app window will open.
It's also useful for users who accidentally activated "Minimize to the System Tray/Menu Bar when closing" and now don't understand how to get the app.

feat(macos): open the main window when the app is reopened

---

app/assets/i18n/strings_nl.json

The existing Dutch translation was outdated, in some places inconsistent (e.g. different forms of address) and contained several errors. This PR improves the translation. I assume `_missing_translations_nl.json` can be discarded afterwards.
Also added a Dutch translation for the website:  
https://github.com/localsend/website/pull/101

Update Dutch (NL) translation

---

app/lib/model/state/settings_state.dart
app/lib/model/state/settings_state.mapper.dart
app/lib/pages/tabs/settings_tab.dart
app/lib/pages/tabs/settings_tab_controller.dart
app/lib/provider/persistence_provider.dart
app/lib/provider/settings_provider.dart

Persist the boolean for 'Advanced Settings', making it more user-friendly.
The thought behind the PR is that users enabling 'Advanced Settings' would like to always have it enabled, and not have to always enable it when closing and opening the application.
**Key Changes:**
- Add persistence for 'Advanced Settings' boolean
**Tested on:**
Windows 10

Add persistence for 'Advanced Settings'

---

app/assets/i18n/_missing_translations_fr.json
app/assets/i18n/strings_fr.json

- updated missing fr translations 
- ran `dart run slang apply --locale=fr`

update: missing fr i18n translations

---

app/lib/util/native/file_picker.dart

Following https://github.com/localsend/localsend/issues/1866
I did manage to build the app to test the change. It seems to be working when running on ipad. It also seems to be working on iphone simulator. 
Please let me know if there is any reason not to do this change, as it seems like it was left out on purpose.

file_picker: add clipboard option to iOS.

---

app/lib/pages/about/translators.dart
readme_i18n/README_ID.md

— README_ID.md was giving 404 while redirecting to duplicate readme_i18n folder,
— also added my contact to the translators.

Fixed README_ID.md redirect and updated translators.dart

---

app/lib/util/native/tray_helper.dart

This fixes the missing tray icon issue on the Flatpak package.
Please note that for this fix to work, the tray icon must be installed to `/app/share/icons/hicolor/*x*/apps/org.localsend.localsend_app-tray.png` when packaging for Flatpak.
If this gets merged, I'll send a pull request to the Flatpak repository, which will install the tray icon to the location above.
Closes #1788

Linux: Use different tray icon path for Flatpak

---

app/assets/i18n/_missing_translations_pt_BR.json

I added the missing PT-BR translations, but for some reason the command `dart run slang apply --locale=pt-BR` is not working. Can someone run it?

i18n: add missing translations

---

app/assets/i18n/_missing_translations_zh_HK.json
app/assets/i18n/strings.json
app/assets/i18n/strings_ja.json
app/assets/i18n/strings_zh-CN.json
app/assets/i18n/strings_zh-HK.json
app/assets/i18n/strings_zh-TW.json

Added `zh-HK` translations and addressed some inconsistencies in `zh-TW` and `zh-CN` translations.
Notably:
| en | zh |
|:---:|:---:|
| exit | 離開／离开 |
| quit | 退出 |
| close | 關閉／关闭 |

Update (mainly) zh-* Translations for v1.16

---

app/lib/provider/network/server/controller/send_controller.dart

bugfix for #2043 
because the file length  will cached on file open; 
so http reponse length use older data(if file be replace with same name on download);
so the chrome download will be fail;
fix:
- on download event reload file length

fixbug #2043

---

app/macos/Runner/Base.lproj/MainMenu.xib
app/macos/ShareExtension/Info.plist

Fixes #2059
Fix the incorrect window name "APP_NAME" on macOS.
* Update `app/macos/Runner/Base.lproj/MainMenu.xib` to change the `CFBundleDisplayName` key to "LocalSend".
* Add `CFBundleDisplayName` key with value "LocalSend" in `app/macos/ShareExtension/Info.plist`.

Fix incorrect APP_NAME on macOS

---

app/assets/CHANGELOG.md
app/lib/pages/web_send_page.dart

fix: black screen when tapping on "Back" twice in "Share via link"

---

app/lib/util/native/file_picker.dart
app/pubspec.lock
app/pubspec.yaml

fixes #872
Alternatively, we can request pasteboard to make this change. Their Mac [mac](https://github.com/MixinNetwork/flutter-plugins/blob/b2beb15590f7b6c38e650ae501923b9bd3e7849c/packages/pasteboard/macos/Classes/PasteboardPlugin.swift#L42-L47) and [Linux](https://github.com/MixinNetwork/flutter-plugins/blob/b2beb15590f7b6c38e650ae501923b9bd3e7849c/packages/pasteboard/linux/pasteboard_plugin.cc#L92) native codes are already converting image buffer to png.
pasteboard's bmp seems to discard alpha channel, so transparency is already lost.
Even with this limitation, I would guess this already covers most use cases
Screenshot:
I have only tested this change on Windows, but don't expect this to be an issue with any other platform
Apologies for the half-baked PR. I have never used …

feat: Convert Clipboard image to png

---

readme_i18n/README_ES.md
readme_i18n/README_FA.md
readme_i18n/README_FR.md
readme_i18n/README_ID.md
readme_i18n/README_IT.md
readme_i18n/README_JA.md
readme_i18n/README_KM.md
readme_i18n/README_KO.md
readme_i18n/README_PH.md
readme_i18n/README_PL.md
readme_i18n/README_PT_BR.md
readme_i18n/README_TH.md
readme_i18n/README_TR.md
readme_i18n/README_VI.md
readme_i18n/README_ZH.md

This PR fixes the Brazilian Portuguese translation in the `README.md` file. Several sections were updated to ensure the translation is accurate and easy to understand for Portuguese-speaking users. The changes include:
- Corrected translation of sections related to contributing, bug fixes and improvements.
- Added troubleshooting section.
- Fixed minor language inconsistencies and clarified some technical terms to improve comprehension.

Fix README translation to Brazilian Portuguese

---

app/lib/provider/network/server/controller/receive_controller.dart

fix: text message content size is not calculated correctly

---

app/lib/provider/network/server/controller/receive_controller.dart
app/lib/widget/dialogs/file_info_dialog.dart

Fixed: content of the text message in the history info dialog box was written three times
Before:
Fix:

fix: content of the text message written three times

---

app/android/app/src/main/kotlin/org/localsend/localsend_app/MainActivity.kt
app/ios/Runner/AppDelegate.swift
app/lib/provider/persistence_provider.dart
app/lib/util/native/channel/android_channel.dart
app/lib/util/native/ios_channel.dart
app/lib/util/native/macos_channel.dart
app/lib/util/ui/animations_status.dart
app/macos/Runner/AppDelegate.swift

Resolves #2333 on Andriod,IOS and MacOS
fetches system animations state on initial startup and toggles animations toggle based on that.
Andriod - tested and is working fine.
IOS and MacOS - Additional Testing is required.

FEAT #2333 Defaults to System Animations on Initial startup (andriod,ios and macos)

---

app/lib/config/init.dart
app/macos/Runner/Info.plist

Currently when logging in (when `Autostart after login` is enabled) LocalSend appears in the Dock for a few seconds, even with `Autostart: Start hidden`, this PR improves the UX so that if `Autostart: Start hidden` is enabled, the icon will not appear at all

feat: enable silent startup using `LSUIElement`

---

app/lib/util/file_path_helper.dart
app/test/unit/util/file_path_helper_test.dart

Updated file duplication naming to a more user-friendly format.
Fixing: #2391
Previous: file.txt → file-1.txt
Now: file.txt → file (1).txt → file (2).txt

Update files name duplicate counter (#2391)

---

app/macos/Runner.xcodeproj/project.pbxproj
app/macos/Runner/Release.entitlements

Hardened Runtime is already enabled in the DMG version ([`compile_mac_dmg.sh` uses `codesign --options runtime`](https://github.com/localsend/localsend/blob/2823bee06236ff2108d37d99e31e8ddebb18ae64/scripts/compile_mac_dmg.sh#L15)).
By explicitly enabling it in the xcodeproj, the Mac App Store version will also be protected, increasing security.
Closes #2085, see https://github.com/localsend/localsend/issues/2085#issuecomment-3316238857

fix: enable Hardened Runtime for Mac App Store vesion

---

app/lib/widget/watcher/shortcut_watcher.dart

Closes https://github.com/localsend/localsend/issues/2261
However, it seems that the keyboard shortcut just randomly stops working; when it doesn't work, the Cmd+W shortcut (line 29) also stops working

feat(macos): add command-comma shortcut to open settings

---

app/lib/config/theme.dart

- 针对 Linux 系统，为不同语言指定了合适的字体：
- 中文（简体）：Noto Sans CJK SC
- 中文（繁体）：Noto Sans CJK TC
- 日文：Noto Sans CJK JP
- 韩文：Noto Sans CJK KR
- 中文、日文和韩文现在可以正常显示
- 已在 Ubuntu 和银河麒麟系统上测试通过
- Add CJK font support for Linux by specifying appropriate fonts per language:
- Chinese (Simplified): Noto Sans CJK SC
- Chinese (Traditional): Noto Sans CJK TC
- Japanese: Noto Sans CJK JP
- Korean: Noto Sans CJK KR
- Chinese, Japanese, and Korean now display correctly on Linux
- Tested on Ubuntu and Kylin Linux
Before:
After:

fix: Add CJK font support for Linux to fix display issues for Chinese, Japanese, and Korean
